---
name: Parcel
strategy: polling
refresh_interval: 60
polling_verb: get
polling_url: "https://api.parcel.app/external/deliveries/?filter_mode=##{{ filter_mode }}"
polling_headers: "api-key=##{{ api_key }}"
no_screen_padding: 'no'
dark_mode: 'no'
custom_fields:
  - keyname: api_key
    name: Parcel API Key
    field_type: text
  - keyname: filter_mode
    name: Filter Mode
    field_type: select
    options:
      - recent
      - active
